version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # Root password from .env
      - MYSQL_DATABASE=${MYSQL_DATABASE}   
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}  # 
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
     interval: 10s
     retries: 5
     start_period: 30s
     timeout: 10s
 
  ecommerce:
    build: .
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app-network
    container_name: ecommerce
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - db
     

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
