version: '3.8'

services:
  ecommerce:
    build:
      context: ./   
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app-network
    container_name: ecommerce
    volumes:
      - ./:/app

networks:
  app-network:
    driver: bridge
